### PR TITLE
Issue 177 : Fix Errors encountered while running the sysbot 

### LINKED ISSUE #177: Fix Errors encountered while running the bot.
## Description
As a developer,
I need to fix the errors encountered while running the bot
so that I can make changes and work on it .

### Update [Required]
- [ ] Comment `"""` wasn't closed in dictionaries.py ,thus it commented whole `dictionaries.py` file.
- [ ] While running project, it gave `encoding error` as the encoding line wasn't being recognised.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.15 hours

### PR DESCRIPTION
**Pull request by CleverFool77**
### Description
While running the bot, Following errors were encountered
1.Changed encoding line at messages.py to be at top so that it can be recognized.
2. Add missing ' " ' in line 1 of dictionaries.py so hat comment is closed.

Fixes #177 

### Type of Change:
Bug fixing

- Code
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Error free execution of `python main_server.py` 

### Checklist:
- [x] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by CleverFool77** [comment]
@sammy1997 Can i know what was left out from PR template.

**Comment by sammy1997** [comment]
@CleverFool77 you are missing the "### How Has This Been Tested?" header. Also, can you squash the 2 commits into one?

**Comment by CleverFool77** [comment]
Actually two different changes were done in diffrent files, that's why I made two commits.

**Comment by CleverFool77** [comment]
@ramitsawhney27 I'll keep that in mind. Thanks for reviewing

**Comment by CleverFool77** [comment]
@ramitsawhney27 I'll keep that in mind. Thanks for reviewing
And utf-8 encoding was not removed, it was put to top so that it can be recognised as it was giving error.I encountered this error while setting up sysbot locally.

**Comment by CleverFool77** [comment]
@ramitsawhney27 @sammy1997  I have updated my PR with the required changes.

**Pull request merged**
