### PR TITLE
Refactor code

### LINKED ISSUE #75: Refactoring the code
## Description
As a developer,
I need to refactor the code,
so that the files can be arranged better.

### Update [Required]
- [ ] Refactor the code and ensure everything works well!

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 mins

### PR DESCRIPTION
**Pull request by sammy1997**
# Description
Refactored the code into directories to make the repository more clean and organized

Fixes #75 

# Type of Change:
- Quality Assurance
- Documentation

# How Has This Been Tested?
-N.A-

# Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sammy1997** [comment]
@ramitsawhney27 Please merge this only after merging #80

**Comment by sammy1997** [comment]
@sara-02 Tree command? Don't get it !

**Comment by sara-02** [comment]
@sammy1997 
```
cd sysbot
tree
```
https://www.geeksforgeeks.org/tree-command-unixlinux/

**Comment by ramitsawhney27** [comment]
@sammy1997 I've merged #80, there are still some conflicts. You could resolve this and we'll merge it.

**Comment by sammy1997** [comment]
@ramitsawhney27 @sara-02 This conflict will be complicated to solve. I will close this PR and send one with the next change

**Comment by sara-02** [comment]
@sammy1997 Sure. Whatever you think best

**Pull request closed without merging**
